[toolchain]
anchor_version = "0.31.0"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fund_manager = "FundManager11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
